language: matlab 
jobs:
  include:
    - os: linux
      dist: bionic
      matlab: R2019b    
    - os: linux
      dist: bionic
      matlab: R2020a
    - os: linux
      dist: focal
      matlab: R2020b    
    - os: linux
      dist: focal
      matlab: R2021a
script: matlab -batch 'disp("Hello World");'
