language: matlab 

jobs:
  include:
    - os: linux
      dist: bionic
      matlab: R2020a
    - os: linux
      dist: focal
      matlab: R2020b    

compiler: gcc

script: 
  - matlab -batch 'disp("Hello World");'
  - matlab -batch 'TROPIC_add_path();'
