language: matlab 

jobs:
  include:
    - os: linux
      dist: bionic
      matlab: R2020a   

compiler: gcc

script: 
  - matlab -batch 'TROPIC_add_path(), cd examples/spatial-12-dof-biped/, main;'
