language: matlab 

jobs:
  include:
    - os: linux
      dist: bionic
      matlab: R2020a
    - os: linux
      dist: focal
      matlab: R2020b    

compiler: gcc

script: 
  - matlab -batch 'TROPIC_add_path();'
  - matlab -batch 'cd examples/planar-7-dof-biped/, main;'
